this is actually funny:
mgcc -o bdftopcf -O2 -Wall -Wpointer-arith -Os -fweb -frename-registers -Wformat -Wstrict-aliasing  -Wbounded -fwrapv -fno-align-functions -fno-align-labels  -falign-loops=4 -falign-jumps=4 -march=i486 -mpush-args -mpreferred-stack-boundary=2 -fhonour-copts      -L../../exports/lib   bdftopcf.o -lXfont -lfntstubs -lfreetype -lz -Wl,-O2  -lz -lm   -Wl,-rpath,/usr/X11R6/lib -Wl,-rpath-link,../../exports/lib
../../exports/lib/libXfont.so.1.5: warning: strcpy() is almost always misused, consider using strlcpy()
../../exports/lib/libXfont.so.1.5: warning: strcat() is almost always misused, consider using strlcat()
../../exports/lib/libXfont.so.1.5: warning: sprintf() is often misused, consider using snprintf()
../../exports/lib/libfreetype.so.11.1: undefined reference to `af_cjk_hints_apply'
../../exports/lib/libfreetype.so.11.1: undefined reference to `af_cjk_metrics_init'
../../exports/lib/libfreetype.so.11.1: undefined reference to `af_cjk_metrics_scale'
../../exports/lib/libfreetype.so.11.1: undefined reference to `af_cjk_hints_init'
collect2: ld returned 1 exit status
*** Error code 1

the afindic.c autofitter uses some internal symbols from
the afcjk.c autofitter, which are defined with the static
qualifier inside there – remove that, now we can link
against the new libfreetype