this, llvm port would look like when both are taken from svn ⇒ still doesn’t work…
Message-ID: <Pine.BSM.4.64L.0811021642240.31401@herc.mirbsd.org>
reported this upstream:

llvm[4]: Compiling BasicConstraintManager.cpp for Release-Asserts build
mpcxx -I/usr/ports/lang/llvm/w-llvm-58565-0/llvm/include -I/usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis  -DNDEBUG -I/usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/../../include -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -O3  -fno-exceptions -fno-rtti -Woverloaded-virtual -pedantic -Wall -W -Wwrite-strings -Wno-long-long -Wunused -Wno-unused-parameter  -c BasicConstraintManager.cpp -o /usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/Release-Asserts/BasicConstraintManager.o
In file included from /usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/../../include/clang/Analysis/PathSensitive/Store.h:18,
                 from /usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/../../include/clang/Analysis/PathSensitive/ConstraintManager.h:18,
                 from BasicConstraintManager.cpp:15:
/usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/../../include/clang/Analysis/PathSensitive/MemRegion.h:246: error: base `clang::AnonTypedRegion' with only non-default constructor in class without a constructor
gmake[4]: *** [/usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis/Release-Asserts/BasicConstraintManager.o] Error 1
gmake[4]: Leaving directory `/usr/ports/lang/llvm/w-llvm-58565-0/llvm/tools/clang/lib/Analysis'